
from gll.__common import __common

_T = __common.T

@__common.t.runtime_checkable
class SupportsIAdd(__common.t.Protocol[_T]):
    def __iadd__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsISub(__common.t.Protocol[_T]):
    def __isub__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsIAddISub(__common.t.Protocol[_T]):
    def __iadd__(self, /, other): ...
    def __isub__(self, /, other): ...

@__common.t.runtime_checkable
class SupportsIMul(__common.t.Protocol[_T]):
    def __imul__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsITruediv(__common.t.Protocol[_T]):
    def __itruediv__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsIFloordiv(__common.t.Protocol[_T]):
    def __ifloordiv__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsITruedivIFloordiv(__common.t.Protocol[_T]):
    def __itruediv__(self, /, other): ...
    def __ifloordiv__(self, /, other): ...
@__common.t.runtime_checkable
class SupportsIMulITruedivIFloordiv(__common.t.Protocol[_T]):
    def __imul__(self, /, other): ...
    def __itruediv__(self, /, other): ...
    def __ifloordiv__(self, /, other): ...

@__common.t.runtime_checkable
class SupportsIMod(__common.t.Protocol[_T]):
    def __imod__(self, /, other): ...
