
from glite import __common

_T = __common.T

@__common.t.runtime_checkable
class SupportsTrunc(__common.t.Protocol[_T]):
    def __trunc__(self, /): ...
@__common.t.runtime_checkable
class SupportsFloor(__common.t.Protocol[_T]):
    def __floor__(self, /): ...
@__common.t.runtime_checkable
class SupportsCeil(__common.t.Protocol[_T]):
    def __ceil__(self, /): ...
@__common.t.runtime_checkable
class SupportsFloorCeil(__common.t.Protocol[_T]):
    def __floor__(self, /): ...
    def __ceil__(self, /): ...
@__common.t.runtime_checkable
class SupportsFloorTrunc(__common.t.Protocol[_T]):
    def __floor__(self, /): ...
    def __trunc__(self, /): ...
@__common.t.runtime_checkable
class SupportsFloorCeilTrunc(__common.t.Protocol[_T]):
    def __floor__(self, /): ...
    def __ceil__(self, /): ...
    def __trunc__(self, /): ...
