
from gll.__common import __common

_T = __common.T


@__common.t.runtime_checkable
class SupportsDescriptorGet(__common.t.Protocol[__common.T]):
    def __get__(self, /, instance, owner): ...
@__common.t.runtime_checkable
class SupportsDescriptorSet(__common.t.Protocol[__common.T]):
    def __set__(self, instance, value): ...
@__common.t.runtime_checkable
class SupportsDescriptorDelete(__common.t.Protocol[__common.T]):
    def __delete__(self, instance): ...

@__common.t.runtime_checkable
class SupportsDescriptorGetSet(__common.t.Protocol[__common.T]):
    def __get__(self, /, instance, owner): ...
    def __set__(self, instance, value): ...
@__common.t.runtime_checkable
class SupportsDescriptorGetSetDelete(__common.t.Protocol[__common.T]):
    def __get__(self, /, instance, owner): ...
    def __set__(self, instance, value): ...
    def __delete__(self, instance): ...
